# Generated by Django 2.0.3 on 2018-04-13 21:26

import descriptor.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', related_query_name='subcategory', to='descriptor.Category')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('count_members', models.PositiveSmallIntegerField(null=True)),
                ('count_guests', models.PositiveSmallIntegerField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', related_query_name='meeting', to='descriptor.Group')),
            ],
            options={
                'db_table': 'meetings',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.BooleanField(default=True)),
                ('newsletter', models.BooleanField(default=True)),
                ('speech_confirm', models.BooleanField(default=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', related_query_name='member', to='descriptor.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('appearance_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField(null=True)),
                ('categories', models.ManyToManyField(to='descriptor.Category')),
            ],
            options={
                'db_table': 'recommendation',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('appearance_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField(null=True)),
                ('fulfilled_positively', models.NullBooleanField()),
                ('categories', models.ManyToManyField(to='descriptor.Category')),
            ],
            options={
                'db_table': 'requirements',
            },
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_file', models.FileField(max_length=255, null=True, upload_to=descriptor.utils.sound_file_path)),
                ('date', models.DateField(auto_now_add=True)),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speeches', related_query_name='speech', to='descriptor.Meeting')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', related_query_name='speech', to='descriptor.Person')),
            ],
            options={
                'db_table': 'speeches',
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', related_query_name='requirement', to='descriptor.Speech'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', related_query_name='recommendation', to='descriptor.Speech'),
        ),
    ]
