# Generated by Django 2.0.3 on 2018-04-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0002_auto_20180414_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speeches', related_query_name='speech', to='descriptor.Person'),
        ),
    ]
