# Generated by Django 2.0.3 on 2018-06-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0005_auto_20180611_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdescription',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
